/**
 * Server-authoritative TMUA answer-key registry.
 *
 * SECURITY:
 * Trusted TMUA scoring must use these keys rather than
 * browser-supplied correct_answers, score or tmua_score9.
 *
 * Do not import this module from client components.
 */

export const TMUA_CANONICAL_KEY_VERSION =
  "tmua-canonical-keys-20260809-v1" as const;

export type TmuaCanonicalStructure =
  "full" | "paper1" | "paper2";

export type TmuaCanonicalTest = {
  readonly testId: string;
  readonly keyVersion: string;
  readonly sourceCommit: string;
  readonly sourceFile: string;
  readonly structure: TmuaCanonicalStructure;
  readonly expectedQuestions: number;
  readonly paper1Range: readonly [number, number] | null;
  readonly paper2Range: readonly [number, number] | null;
  readonly canonicalSha256: string;
  readonly answers: readonly string[];
};

/* TMUA_CANONICAL_JSON_START */
export const TMUA_CANONICAL_TESTS =
{
  "full-mock-01-all-topics": {
    "testId": "full-mock-01-all-topics",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-mock-01-all-topics.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "b7826e64e66e339e77be7ce4b94cc55ae36b5e5d30428fb7c8a5da8010c24940",
    "answers": [
      "C",
      "A",
      "A",
      "C",
      "B",
      "B",
      "D",
      "E",
      "D",
      "A",
      "D",
      "A",
      "A",
      "C",
      "E",
      "A",
      "B",
      "E",
      "E",
      "E",
      "B",
      "D",
      "B",
      "C",
      "D",
      "D",
      "A",
      "A",
      "A",
      "D",
      "C",
      "C",
      "B",
      "D",
      "D",
      "A",
      "D",
      "A",
      "C",
      "E"
    ]
  },
  "full-mock-02-all-topics": {
    "testId": "full-mock-02-all-topics",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-mock-02-all-topics.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "1e876c64f36baae0fb0a3f8c9472b2667e869010fa24f8091f930ec344eb5148",
    "answers": [
      "B",
      "F",
      "E",
      "A",
      "A",
      "C",
      "E",
      "C",
      "C",
      "D",
      "B",
      "C",
      "D",
      "B",
      "A",
      "D",
      "E",
      "B",
      "D",
      "E",
      "C",
      "D",
      "B",
      "B",
      "D",
      "G",
      "B",
      "A",
      "D",
      "C",
      "D",
      "D",
      "G",
      "D",
      "E",
      "A",
      "E",
      "C",
      "D",
      "C"
    ]
  },
  "full-official-2016": {
    "testId": "full-official-2016",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2016.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "cfc828b43ec90e52c8b24c5d551841cfacbe03137e770d36fced50165ab6ca9a",
    "answers": [
      "H",
      "E",
      "C",
      "B",
      "C",
      "C",
      "B",
      "F",
      "D",
      "E",
      "E",
      "E",
      "C",
      "D",
      "C",
      "C",
      "D",
      "A",
      "B",
      "D",
      "A",
      "B",
      "D",
      "C",
      "C",
      "C",
      "C",
      "B",
      "D",
      "E",
      "D",
      "F",
      "E",
      "B",
      "D",
      "C",
      "H",
      "D",
      "F",
      "E"
    ]
  },
  "full-official-2017": {
    "testId": "full-official-2017",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2017.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "a4119db772ea95f3852204614f9d0f1f726d02b2f20a3fc2d8c99f4bc61f0d53",
    "answers": [
      "C",
      "C",
      "A",
      "B",
      "C",
      "B",
      "B",
      "A",
      "F",
      "E",
      "A",
      "B",
      "C",
      "F",
      "B",
      "E",
      "D",
      "A",
      "D",
      "E",
      "A",
      "E",
      "G",
      "B",
      "B",
      "A",
      "E",
      "E",
      "D",
      "D",
      "B",
      "C",
      "B",
      "F",
      "D",
      "C",
      "F",
      "B",
      "E",
      "B"
    ]
  },
  "full-official-2018": {
    "testId": "full-official-2018",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2018.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "97e3fec0f6e3e0046fde6a6b1c9d8267e4c65340eaed34f78fd874afefb968cf",
    "answers": [
      "D",
      "C",
      "E",
      "G",
      "D",
      "E",
      "A",
      "D",
      "B",
      "E",
      "C",
      "F",
      "C",
      "B",
      "E",
      "F",
      "A",
      "B",
      "D",
      "E",
      "C",
      "B",
      "F",
      "D",
      "A",
      "C",
      "B",
      "D",
      "F",
      "B",
      "A",
      "F",
      "F",
      "E",
      "G",
      "F",
      "C",
      "C",
      "C",
      "B"
    ]
  },
  "full-official-2019": {
    "testId": "full-official-2019",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2019.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "890877c46c129aee63249c757b7207db9080a7aec8ee69d988da5efb5b447bcc",
    "answers": [
      "A",
      "A",
      "E",
      "C",
      "E",
      "C",
      "F",
      "E",
      "D",
      "F",
      "H",
      "C",
      "B",
      "B",
      "A",
      "C",
      "C",
      "B",
      "C",
      "E",
      "E",
      "C",
      "A",
      "D",
      "B",
      "D",
      "B",
      "E",
      "C",
      "A",
      "A",
      "F",
      "D",
      "B",
      "B",
      "F",
      "D",
      "E",
      "E",
      "B"
    ]
  },
  "full-official-2020": {
    "testId": "full-official-2020",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2020.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "d0e26427eb26754e5049b8f7b5b47d976399f8b664b8032564cc1ccb38cfbeb5",
    "answers": [
      "C",
      "C",
      "B",
      "D",
      "A",
      "C",
      "A",
      "D",
      "C",
      "A",
      "E",
      "D",
      "F",
      "E",
      "C",
      "C",
      "A",
      "A",
      "E",
      "C",
      "E",
      "F",
      "C",
      "G",
      "A",
      "A",
      "H",
      "E",
      "F",
      "F",
      "G",
      "D",
      "D",
      "A",
      "D",
      "D",
      "E",
      "G",
      "E",
      "C"
    ]
  },
  "full-official-2021": {
    "testId": "full-official-2021",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2021.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "6f88dc25f12430e9861a3d4c44a95c437e894becbd6ae963fc9b21ae430ac450",
    "answers": [
      "F",
      "F",
      "G",
      "B",
      "F",
      "D",
      "G",
      "A",
      "C",
      "B",
      "A",
      "E",
      "C",
      "B",
      "C",
      "B",
      "A",
      "B",
      "B",
      "D",
      "D",
      "E",
      "C",
      "C",
      "B",
      "D",
      "B",
      "C",
      "C",
      "E",
      "C",
      "B",
      "A",
      "C",
      "B",
      "E",
      "F",
      "C",
      "F",
      "E"
    ]
  },
  "full-official-2022": {
    "testId": "full-official-2022",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2022.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "f2a11f3651ff1a62ca55317190b7f867fdcd7483177ea6afadda20d869b1c7f3",
    "answers": [
      "C",
      "D",
      "F",
      "C",
      "H",
      "F",
      "E",
      "B",
      "E",
      "C",
      "A",
      "D",
      "A",
      "D",
      "H",
      "B",
      "D",
      "B",
      "F",
      "B",
      "B",
      "E",
      "C",
      "B",
      "F",
      "C",
      "F",
      "C",
      "A",
      "G",
      "C",
      "F",
      "E",
      "D",
      "F",
      "D",
      "E",
      "E",
      "B",
      "E"
    ]
  },
  "full-official-2023": {
    "testId": "full-official-2023",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-official-2023.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "2b555da7baffc8163ac850a01fe10483a3d5cff04f869563d9935066e793bda2",
    "answers": [
      "F",
      "A",
      "C",
      "C",
      "F",
      "E",
      "F",
      "B",
      "E",
      "B",
      "B",
      "F",
      "F",
      "A",
      "F",
      "E",
      "E",
      "E",
      "D",
      "F",
      "H",
      "F",
      "C",
      "G",
      "A",
      "F",
      "E",
      "D",
      "D",
      "A",
      "G",
      "C",
      "C",
      "F",
      "B",
      "B",
      "F",
      "D",
      "H",
      "D"
    ]
  },
  "full-specimen": {
    "testId": "full-specimen",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/full-specimen.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "fc94c7f7244eecec395513c6dfb57f1cabd60384b117e02dbb2025defc2da4f3",
    "answers": [
      "D",
      "D",
      "B",
      "E",
      "D",
      "D",
      "C",
      "F",
      "A",
      "D",
      "E",
      "D",
      "C",
      "D",
      "A",
      "E",
      "D",
      "B",
      "D",
      "G",
      "B",
      "B",
      "C",
      "A",
      "A",
      "F",
      "C",
      "C",
      "E",
      "E",
      "D",
      "A",
      "C",
      "B",
      "E",
      "A",
      "E",
      "E",
      "B",
      "D"
    ]
  },
  "p1-mock-01-algebra-sequences-functions-geometry": {
    "testId": "p1-mock-01-algebra-sequences-functions-geometry",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p1-mock-01-algebra-sequences-functions-geometry.html",
    "structure": "paper1",
    "expectedQuestions": 20,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": null,
    "canonicalSha256": "91c74cfe41a9086c3171a8a436e1507604d57215c6de08a937e1f4c6e97697ac",
    "answers": [
      "B",
      "D",
      "B",
      "C",
      "D",
      "D",
      "D",
      "B",
      "D",
      "C",
      "D",
      "B",
      "B",
      "D",
      "C",
      "A",
      "E",
      "C",
      "C",
      "D"
    ]
  },
  "p1-mock-02-graphs-trig-logs": {
    "testId": "p1-mock-02-graphs-trig-logs",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p1-mock-02-graphs-trig-logs.html",
    "structure": "paper1",
    "expectedQuestions": 20,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": null,
    "canonicalSha256": "ba5dd06036ff41e547b5828d66b1e3624fee2a70c5c17aa85a5fde6a96bb1942",
    "answers": [
      "D",
      "A",
      "D",
      "G",
      "C",
      "F",
      "B",
      "F",
      "E",
      "C",
      "B",
      "B",
      "D",
      "B",
      "B",
      "B",
      "E",
      "A",
      "C",
      "D"
    ]
  },
  "p1-mock-03-calculus": {
    "testId": "p1-mock-03-calculus",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p1-mock-03-calculus.html",
    "structure": "paper1",
    "expectedQuestions": 20,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": null,
    "canonicalSha256": "49e83c632788265168c8ac248dfefedeb2eca06c416e5d74c66bdde60ed04ae7",
    "answers": [
      "A",
      "C",
      "C",
      "D",
      "A",
      "B",
      "F",
      "C",
      "A",
      "B",
      "D",
      "A",
      "D",
      "B",
      "D",
      "F",
      "A",
      "D",
      "D",
      "E"
    ]
  },
  "p2-mock-04-logic-proofs": {
    "testId": "p2-mock-04-logic-proofs",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p2-mock-04-logic-proofs.html",
    "structure": "paper2",
    "expectedQuestions": 20,
    "paper1Range": null,
    "paper2Range": [
      0,
      20
    ],
    "canonicalSha256": "82dc69d8e56e1fc6581d5ac2421cf8848b404720af803c3b2e1f19cb00620122",
    "answers": [
      "C",
      "F",
      "C",
      "B",
      "B",
      "C",
      "D",
      "E",
      "C",
      "D",
      "E",
      "D",
      "C",
      "H",
      "C",
      "D",
      "F",
      "A",
      "D",
      "B"
    ]
  },
  "p1-mock-05-all-topics": {
    "testId": "p1-mock-05-all-topics",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p1-mock-05-all-topics.html",
    "structure": "paper1",
    "expectedQuestions": 20,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": null,
    "canonicalSha256": "b1fd765fbd274b1e003c66441d37a99fecb3a4d1cd3f208d55e4c6f55d5240ba",
    "answers": [
      "B",
      "A",
      "D",
      "D",
      "D",
      "D",
      "D",
      "A",
      "C",
      "D",
      "H",
      "E",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "C",
      "B"
    ]
  },
  "p2-mock-06-all-topics": {
    "testId": "p2-mock-06-all-topics",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/p2-mock-06-all-topics.html",
    "structure": "paper2",
    "expectedQuestions": 20,
    "paper1Range": null,
    "paper2Range": [
      0,
      20
    ],
    "canonicalSha256": "bcbe0814353ad0e02d7fe20fc2b63f322599ab8ff0175514320f217022873ba3",
    "answers": [
      "D",
      "B",
      "A",
      "C",
      "A",
      "D",
      "B",
      "D",
      "C",
      "E",
      "E",
      "D",
      "E",
      "D",
      "D",
      "B",
      "D",
      "E",
      "C",
      "C"
    ]
  },
  "tmua-2024-2025-challenging-mock": {
    "testId": "tmua-2024-2025-challenging-mock",
    "keyVersion": "tmua-canonical-keys-20260809-v1",
    "sourceCommit": "ddb8e29",
    "sourceFile": "public/practice-tests/tests/tmua-2024-2025-challenging-mock/index.html",
    "structure": "full",
    "expectedQuestions": 40,
    "paper1Range": [
      0,
      20
    ],
    "paper2Range": [
      20,
      40
    ],
    "canonicalSha256": "7bb556c1aed493a17a62de139edb8cfa0a85d07d7dd1d7354f4f835869468ae7",
    "answers": [
      "E",
      "A",
      "B",
      "A",
      "E",
      "B",
      "C",
      "A",
      "E",
      "C",
      "B",
      "E",
      "D",
      "C",
      "A",
      "D",
      "E",
      "D",
      "B",
      "C",
      "C",
      "B",
      "B",
      "C",
      "A",
      "E",
      "A",
      "A",
      "D",
      "E",
      "C",
      "D",
      "A",
      "B",
      "C",
      "B",
      "E",
      "D",
      "A",
      "B"
    ]
  }
} as const;
/* TMUA_CANONICAL_JSON_END */

export function getCanonicalTmuaTest(
  testId: string,
): TmuaCanonicalTest | null {
  const key = String(testId || "").trim();

  const registry =
    TMUA_CANONICAL_TESTS as unknown as
      Readonly<Record<string, TmuaCanonicalTest>>;

  return registry[key] ?? null;
}
